import {
  AndroidOutlined,
  AppleOutlined,
  WindowsOutlined,
  IeOutlined,
  ChromeOutlined,
  GithubOutlined,
  AliwangwangOutlined,
  DingdingOutlined,
  WeiboCircleOutlined,
  WeiboSquareOutlined,
  TaobaoCircleOutlined,
  Html5Outlined,
  WeiboOutlined,
  TwitterOutlined,
  WechatOutlined,
  YoutubeOutlined,
  AlipayOutlined,
  AlipayCircleOutlined,
  TaobaoOutlined,
  SkypeOutlined,
  QqOutlined,
  MediumOutlined,
  GitlabOutlined,
  CodepenOutlined,
  CodeSandboxOutlined,
  AmazonOutlined,
  GoogleOutlined,
  ZhihuOutlined,
  SlackOutlined,
  DribbbleOutlined,
  InstagramOutlined,
  RedditOutlined,
  SketchOutlined,
  AntDesignOutlined,
} from '@ant-design/icons';

export const brandIcons = {
  'android': AndroidOutlined,
  'apple': AppleOutlined,
  'windows': WindowsOutlined,
  'ie': IeOutlined,
  'chrome': ChromeOutlined,
  'github': GithubOutlined,
  'aliww': AliwangwangOutlined,
  'dingding': DingdingOutlined,
  'weibo:s': WeiboSquareOutlined,
  'weibo:c': WeiboCircleOutlined,
  'taobao:c': TaobaoCircleOutlined,
  'html5': Html5Outlined,
  'weibo': WeiboOutlined,
  'twitter': TwitterOutlined,
  'wechat': WechatOutlined,
  'youtube': YoutubeOutlined,
  'alipay:c': AlipayCircleOutlined,
  'alipay': AlipayOutlined,
  'taobao': TaobaoOutlined,
  'skype': SkypeOutlined,
  'qq': QqOutlined,
  'medium': MediumOutlined,
  'gitlab': GitlabOutlined,
  'codepen': CodepenOutlined,
  'codesandbox': CodeSandboxOutlined,
  'amazon': AmazonOutlined,
  'google': GoogleOutlined,
  'zhihu': ZhihuOutlined,
  'slack': SlackOutlined,
  'dribbble': DribbbleOutlined,
  'instagram': InstagramOutlined,
  'reddit': RedditOutlined,
  'sketch': SketchOutlined,
  'antdesign': AntDesignOutlined,
};
